version: '3'

services:

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: quickBiller
      POSTGRES_PASSWORD: paswoord
      POSTGRES_DB: database
      PGDATA: /var/lib/postgresql/data/postgres-data
    logging:
      options:
        max-size: 100m
        max-file: "12"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql